[project]
name = "projet-these"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Lucas Guillerot", email = "lucas.guillerot@ias.u-psud.fr" },
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
]
